services:
  - type: web
    name: waha-cozil
    env: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    plan: free
    envVars:
      - key: WAHA_VERSION
        value: latest
      - key: WAHA_LOG_LEVEL
        value: info
      - key: WAHA_WEBHOOK_URL
        value: 
      - key: WAHA_WEBHOOK_EVENTS
        value: message
      - key: AUTH_ENABLED
        value: "false"
      - key: WAHA_AUTH_ENABLED
        value: "false"
      - key: ENABLE_AUTH
        value: "false"
      - key: AUTH_DISABLED
        value: "true"
      - key: DISABLE_AUTH
        value: "true"

